name: Build Flatpak

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.7
      options: --privileged
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Generate Python dependencies
      run: |
        # Install pip (container might use different package manager)
        if command -v apt-get >/dev/null 2>&1; then
            apt-get update && apt-get install -y python3-pip
        elif command -v dnf >/dev/null 2>&1; then
            dnf install -y python3-pip
        elif command -v pacman >/dev/null 2>&1; then
            pacman -S --noconfirm python-pip
        else
            # Try to install pip directly
            python3 -m ensurepip --default-pip || curl https://bootstrap.pypa.io/get-pip.py | python3
        fi
        python3 -m pip install --user flatpak-pip-generator
        # Use full path to avoid PATH issues
        $HOME/.local/bin/flatpak-pip-generator --output python3-yt-dlp yt-dlp
        $HOME/.local/bin/flatpak-pip-generator --output python3-requests requests
    
    - name: Build Flatpak
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: yt-leechr.flatpak
        manifest-path: com.github.buggerman.yt-leechr.json
        cache-key: flatpak-builder-${{ github.sha }}
    
    - name: Upload Flatpak artifact
      uses: actions/upload-artifact@v4
      with:
        name: YT-Leechr-flatpak
        path: yt-leechr.flatpak
        retention-days: 30
    
    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: yt-leechr.flatpak
        draft: true
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}