name: Build Flatpak

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.7
      options: --privileged
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Generate Python dependencies
      run: |
        # Install pip (container might use different package manager)
        if command -v apt-get >/dev/null 2>&1; then
            apt-get update && apt-get install -y python3-pip
        elif command -v dnf >/dev/null 2>&1; then
            dnf install -y python3-pip
        elif command -v pacman >/dev/null 2>&1; then
            pacman -S --noconfirm python-pip
        else
            # Try to install pip directly
            python3 -m ensurepip --default-pip || curl https://bootstrap.pypa.io/get-pip.py | python3
        fi
        python3 -m pip install --user flatpak-pip-generator
        # Debug: check where it was installed
        echo "HOME is: $HOME"
        echo "Contents of ~/.local/bin:"
        ls -la ~/.local/bin/ || echo "Directory doesn't exist"
        echo "Looking for flatpak-pip-generator:"
        find ~ -name "flatpak-pip-generator" -type f 2>/dev/null || echo "Not found in home"
        find /usr -name "flatpak-pip-generator" -type f 2>/dev/null || echo "Not found in /usr"
        # Try to find and run it
        GENERATOR=$(find ~ -name "flatpak-pip-generator" -type f 2>/dev/null | head -1)
        if [ -n "$GENERATOR" ]; then
            echo "Found generator at: $GENERATOR"
            $GENERATOR --output python3-yt-dlp yt-dlp
            $GENERATOR --output python3-requests requests
        else
            echo "ERROR: Could not find flatpak-pip-generator"
            exit 1
        fi
    
    - name: Build Flatpak
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: yt-leechr.flatpak
        manifest-path: com.github.buggerman.yt-leechr.json
        cache-key: flatpak-builder-${{ github.sha }}
    
    - name: Upload Flatpak artifact
      uses: actions/upload-artifact@v4
      with:
        name: YT-Leechr-flatpak
        path: yt-leechr.flatpak
        retention-days: 30
    
    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: yt-leechr.flatpak
        draft: true
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}